openapi: "3.0.1"
info:
  title: "dev-serverless-aws-typescript"
  version: "2019-11-19T20:48:49Z"
servers:
- url: "https://3mcv0b9790.execute-api.eu-west-1.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: "/dev"
paths:
  /message/{messageId}:
    get:
      security:
      - authorize: []
    options:
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Credentials:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
  /message:
    get:
      security:
      - authorize: []
    post:
      security:
      - authorize: []
    options:
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Credentials:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
components:
  securitySchemes:
    authorize:
      type: "apiKey"
      name: "Authorization"
      in: "header"
      x-amazon-apigateway-authtype: "custom"
